### Базовый URL
@host = http://localhost:8080
@contentType = application/json


### Создание клиента - успешный кейс
### Ожидаем: 201 Created
POST {{host}}/api/clients
Content-Type: {{contentType}}

{
  "fullName": "Глеб Птеров",
  "gender": "M"
}

### Создание клиента - успешный кейс
### Ожидаем: 201 Created
POST {{host}}/api/clients
Content-Type: {{contentType}}

{
  "fullName": "Мария Смирнова",
  "gender": "F"
}

### Создание клиента - пустое имя
### Ожидаем: 400 Bad Request
POST {{host}}/api/clients
Content-Type: {{contentType}}

{
  "fullName": "",
  "gender": "M"
}

### Создание клиента - gender отсутствует
### Ожидаем: 400 Bad Request
POST {{host}}/api/clients
Content-Type: {{contentType}}

{
  "fullName": "Алексей Петров"
}

### Создание клиента - некорректный gender
### Ожидаем: 400 Bad Request
POST {{host}}/api/clients
Content-Type: {{contentType}}

{
  "fullName": "Некорректный Клиент",
  "gender": "MALE"
}

### Получить список всех клиентов
### Ожидаем: 200 OK
GET {{host}}/api/clients

### Получить клиента по id = 1
### Ожидаем: 200 OK, если клиент существует
GET {{host}}/api/clients/111

### Получить клиента по несуществующему id
### Ожидаем: 404 Not Found
GET {{host}}/api/clients/99999

### Полное/частичное обновление клиента по id = 1
### Ожидаем: 200 OK
PUT {{host}}/api/clients/8
Content-Type: {{contentType}}

{
  "fullName": "Иван Петров",
  "gender": "M",
  "status": "INACTIVE"
}

### Частичное обновление только имени
### Ожидаем: 200 OK
PUT {{host}}/api/clients/8
Content-Type: {{contentType}}

{
  "fullName": "Иван Воронеж"
}

### Обновление несуществующего клиента
### Ожидаем: 404 Not Found
PUT {{host}}/api/clients/99999
Content-Type: {{contentType}}

{
  "fullName": "Не Существует",
  "gender": "F",
  "status": "ACTIVE"
}

### Обновление с некорректным статусом
### Ожидаем: 400 Bad Request
PUT {{host}}/api/clients/1
Content-Type: {{contentType}}

{
  "status": "BLOCKED"
}

### Удаление клиента по id = 1
### Ожидаем: 204 No Content
DELETE {{host}}/api/clients/9

### Повторное удаление того же клиента
### Ожидаем: 404 Not Found
DELETE {{host}}/api/clients/1

### Удаление несуществующего клиента
### Ожидаем: 404 Not Found
DELETE {{host}}/api/clients/99999

###
GET {{host}}/api/clients/active

###
GET {{host}}/api/clients/active/count